/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LabelLog {
  'user' : Principal,
  'timestamp' : Time,
  'actualWeight' : number,
  'materialCode' : string,
}
export interface Material {
  'weight' : number,
  'minWeight' : number,
  'maxWeight' : number,
  'code' : string,
  'description' : string,
  'quantity' : bigint,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateMaterial' : ActorMethod<
    [string, string, number, number, number, bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkImportMaterials' : ActorMethod<[Array<Material>], undefined>,
  'clearAllLabelLogs' : ActorMethod<[], undefined>,
  'clearAllMaterials' : ActorMethod<[], undefined>,
  'deleteMaterial' : ActorMethod<[string], undefined>,
  'generateLabel' : ActorMethod<[string, number], undefined>,
  'getAllLabelLogs' : ActorMethod<[], Array<LabelLog>>,
  'getAllMaterials' : ActorMethod<[], Array<Material>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMaterial' : ActorMethod<[string], [] | [Material]>,
  'getMaterialLabelLogs' : ActorMethod<[string], Array<LabelLog>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
