/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Material = IDL.Record({
  'weight' : IDL.Float64,
  'minWeight' : IDL.Float64,
  'maxWeight' : IDL.Float64,
  'code' : IDL.Text,
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const Time = IDL.Int;
export const LabelLog = IDL.Record({
  'user' : IDL.Principal,
  'timestamp' : Time,
  'actualWeight' : IDL.Float64,
  'materialCode' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateMaterial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Nat],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkImportMaterials' : IDL.Func([IDL.Vec(Material)], [], []),
  'clearAllLabelLogs' : IDL.Func([], [], []),
  'clearAllMaterials' : IDL.Func([], [], []),
  'deleteMaterial' : IDL.Func([IDL.Text], [], []),
  'generateLabel' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'getAllLabelLogs' : IDL.Func([], [IDL.Vec(LabelLog)], ['query']),
  'getAllMaterials' : IDL.Func([], [IDL.Vec(Material)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMaterial' : IDL.Func([IDL.Text], [IDL.Opt(Material)], ['query']),
  'getMaterialLabelLogs' : IDL.Func([IDL.Text], [IDL.Vec(LabelLog)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Material = IDL.Record({
    'weight' : IDL.Float64,
    'minWeight' : IDL.Float64,
    'maxWeight' : IDL.Float64,
    'code' : IDL.Text,
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const Time = IDL.Int;
  const LabelLog = IDL.Record({
    'user' : IDL.Principal,
    'timestamp' : Time,
    'actualWeight' : IDL.Float64,
    'materialCode' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateMaterial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Nat],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkImportMaterials' : IDL.Func([IDL.Vec(Material)], [], []),
    'clearAllLabelLogs' : IDL.Func([], [], []),
    'clearAllMaterials' : IDL.Func([], [], []),
    'deleteMaterial' : IDL.Func([IDL.Text], [], []),
    'generateLabel' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'getAllLabelLogs' : IDL.Func([], [IDL.Vec(LabelLog)], ['query']),
    'getAllMaterials' : IDL.Func([], [IDL.Vec(Material)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMaterial' : IDL.Func([IDL.Text], [IDL.Opt(Material)], ['query']),
    'getMaterialLabelLogs' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LabelLog)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
